# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c28401895cda3f08c023dc6c0a66bef301e78b4a4537ded60aa2588c772ed3515a1812bbd3a73a842ae5c2b89c5008fd64d5dc6e3dd18e749bf669663f88bcbe

test:
  secret_key_base: f26aba11ae27fddc4a9b8b27b28b029d9f139fc8177ac061e4270043c515703f07bf62954c1b2d69d51ce8551b4436e6647cda0bcea1c04ca3686af295f547ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
