# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3b0723a41865847c26d6c6b2c4f90ad52dcd582b947132b020f1f6ce1d0b20468464378a25fd92ea21486b2ec56d2bbf3eb58e742d0b7af4b6c654dc6e9a319

test:
  secret_key_base: c04040504e86abb895741178d3738d63152a16997c30acdf6d7de450269c0475746931f7bd72761f0aea11fb6edbfbeab0fecc67a93483ad9d3a90e2ea8b0549

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
